### PR TITLE
Catch up current mruby (3.0.0) and Rust (1.54.0-nightly)

### PR DESCRIPTION
**Pull request by udzura**
* Use 3.0.0 mruby and re-created mruby-out.tar
* Use Rust 1.54.0 (current nightly), with all of warnings erased (including `std::mem::uninitialized` usage, fixing `try!`s and `gcc` -> `cc` change)

p.s.
I'm afraid I don't know what status this project is, but I have a will to inherit the maintainer role of this project.

Thanks!

### CODE REVIEW

**Comment by Thermatix** [comment]
@udzura do you intend to fork and take over this project? 

Just I want to know if doing the following for all the ruby types (using bool as an example) would be possible:

```rust
impl From<Value> for bool {
    fn from(&self) -> bool {
        match self.typ {
            MrType::MRB_TT_FALSE => false,
            MrType::MRB_TT_TRUE  => true,
            _ => Err(MrubyError::Cast("TrueClass or FalseClass".to_owned()))
        }
    }
}
```

It should also be possible (maybe via a trait?) to `impl From<CustomType>` as well.

What do you think?

EDIT:

I decided to give it a go myself:

https://github.com/udzura/mrusty/pull/1

**Comment by udzura** [comment]
@Thermatix 
* I have forked this project. I'll do some maintenance for my fork, because I'm using it now
* It has not yet been determined who will take over this project.

**Comment by Thermatix** [comment]
Neato, as will I, I personally feel mrusty is the best attempt for integrating ruby scripting into a rust project, rutie is just... super complex and I think it uses MRI, any way I'm glad Someone is developing Mrusty as it would be a shame for it to fall to the side.

**Comment by dragostis** [comment]
@udzura, if you plan to maintain this, I'm happy to hand the repository over to you. 😃

**Comment by udzura** [comment]
@dragostis Yes, I'm willing to!
In recent time I have pushed some commits to my forked master, but I'll organize my commit after getting a maintainer flag.

Do I have anything to do for taking over this project?

**Pull request closed without merging**
